server:
  port: 8072
eureka:
  instance:
    # prefer the IP address of the service rather than the server name
    preferIpAddress: true
  client:
    # register the service with the eureka server
    registerWithEureka: true
    # pulls down a copy of the registry
    fetchRegistry: true
    # sets the location of the eureka service
    serviceUrl:
      defaultZone: 'http://${EUREKA_HOST:localhost}:8070/eureka/'


spring:
  cloud:
    gateway:
      # automated mapping of routes via service discovery
      # Enables the gateway to create routes based on services registered with service discovery
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true
      # manual mapping of routes via service discovery
      routes:
        - id: organization-service
        - uri: lb://organization-service

          predicates:
            - Path=/organization/**

          filters:
            #- StripPrefix=2   # to strip say the first api/v1  say we had api/v1/organization-service but the service has no api/v1
            # Rewrites the request path from /organization/** to /**
            - RewritePath=/organization/(?<path>.*), /$\{path}

management.endpoint.gateway.enabled: true
management.endpoints.web.exposure.include: health,gateway