server:
  port: 8080


example:
  property: I AM THE LICENSE DEFAULT
spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL

    show-sql: true
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true

eureka:
  instance:
    # prefer the IP address of the service rather than the server name
    preferIpAddress: true
  client:
    # register the service with the eureka server
    registerWithEureka: true
    # pulls down a copy of the registry
    fetchRegistry: true
    # sets the location of the eureka service
    serviceUrl:
      defaultZone: 'http://${EUREKA_HOST:localhost}:8070/eureka/'

resilience4j:
  circuitbreaker:
    instances:
      licenseService:
        ## indicate whether to expose the configuration over the health endpoint
        register-health-indicator: true
        ## sets the ring buffer size at closed state: used to evaluate total call to be evaluated in closed state (default: 100)
        ## circuit breaker only opens if the failure rate within this ring buffer > than the failure-rate-threshold
        ring-buffer-size-in-closed-state: 10
        ## sets the ring buffer size at half-open state: used to evaluate total call to be evaluated in half-open state (default: 10)
        ## if the failure rate within the ring buffer is <= to the failure-rate-threshold, its switched to closed else switches to back to open
        ring-buffer-size-in-half-open-state: 3
        ## sets the time the circuit breaker should wait before changing the status from open to half-open (default 60s)
        wait-duration-in-open-state:
          units:
            - 20s
        ## the percentage of the failure rate threshold
        ## when the failure rate in the ring buffer in closed state is >= this threshold, the circuit breaker changes to
        ## open state and starts short-circuiting calls  (default: 50)
        failure-rate-threshold: 7
        # by default all exceptions are seen as failures,
        # however, we can configure the list of exceptions to see as failures
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException

      licenseAlternateService:
        record-exceptions:
          - java.io.IOException

      organizationService:
        register-health-indicator: true
        ring-buffer-size-in-closed-state: 15
        ring-buffer-size-in-half-open-state: 4
        wait-duration-in-open-state:
          units:
            - 20s
        failure-rate-threshold: 9


  bulkhead:
    instances:
      bulkheadLicenseService:
        # max amount time to block a thread (default 0)
        max-wait-duration:
          units:
            - 10ms
        # max concurrent calls (default 25)
        max-concurrent-calls: 2

  thread-pool-bulkhead:
    instances:
      bulkheadLicenseService:
        #(default Runtime.getRuntime().availableProcessors())
        max-thread-pool-size: 1
        #(default Runtime.getRuntime().availableProcessors())
        core-thread-pool-size: 1
        #(default 100)
        queue-capacity: 1
        #(max time that idle thread will wait for new tasks before terminating. default 20ms)
        keep-alive-duration:
          units:
            - 20ms

  retry:
    instances:
      retryLicenseService:
        # maximum retry attempts
        max-attempts: 5
        # wait time before next retry (default 500ms)
        wait-duration: 3s
        # exceptions to retry for (default empty i.e all exceptions)
        retry-exceptions:
          - java.util.concurrent.TimeoutException
        # list of exceptions not to retry for (default empty)
        ignore-exceptions:
          - java.lang.NullPointerException
        # prevent starving/ choking service to retry for to allow breathing room
        ## use exponential back as alternative to wait-duration
        enable-exponential-backoff: true
        # exponential multiplier a=(20 *1.2),   (a * 1.2) ...  (z *1.2)
        exponential-backoff-multiplier: 1.2
        # max exponential wait duration, i.e X.12  <= 10
        exponential-max-wait-duration: 10s
        # retry if result meet condition
        result-predicate: com.optimagrowth.license.resilience.ConditionalRetryResultPredicate
        # this exception used here must be excluded from the retry-exceptions
        retry-exception-predicate: com.optimagrowth.license.resilience.ConditionalRetryExceptionPredicate
        # If you don't want to use a fixed wait duration between retry attempts,
        # you can configure an IntervalFunction which is used instead to calculate the wait duration for every attempt
        #interval-bi-function:

  ratelimiter:
    instances:
      licenceService:
        # time a thread waits for permission (call to be allowed)  default 5s
        timeout-duration: 100s
        # time of refresh period default 500ns
        limit-refresh-period: 5000ns
        # number of calls allowed for a period. default 50
        limit-for-period: 2