example:
  property: I AM THE LICENSE DEFAULT
spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: POSTGRESQL

    show-sql: true
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    platform: postgres
    testWhileIdle: true
    validationQuery: SELECT 1
  database:
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
    enabled-by-default: true